### ISSUE TITLE
[BUG] Programa incapaz de suportar valores de p e q muito grandes

### ISSUE THREAD

**Issue by Arthurpmrs** [srbernardo/rsa#1]
Ao fazer a potência do i-ésimo termo da mensagem encriptada com o valor inverso, o valor resultante era grande de mais para ser suportado pela memória. Pelo que parece existe um limite para o tamanho de um item guardado pela memória.

Referência: https://stackoverflow.com/questions/7604966/maximum-and-minimum-values-for-ints

Para corrigir, substituir a parte da leitura do arquivo e cálculo por isso:
```python
with open('./bruno.txt', 'r') as arquivo:
    msg = arquivo.read().split(" ")

    msg_decriptada = []

    for i in range(0,len(msg)):
      msg_decriptada.append(pow(int(msg[i]), inverso(e, phi), n))
```

A função pow(), interna do Python, recebe como argumento a base, a potência e um valor para tirar o módulo do resultado da potência. Não sei como é a implementação por debaixo dos panos, mas funciona.

Referência: https://stackoverflow.com/questions/23759098/pow-or-for-very-large-number-in-python

OBS: Eu mudei a parte de carregar o arquivo (usando o `with`) , pois ele estava sendo aberto e depois não estava sendo fechado pelo que eu vi, isso pode dar problema caso um erro aconteça, o arquivo continua aberto.

**Comment by srbernardo** [comment]
Aprovado

**Comment by srbernardo** [comment]
top
